trainer:
  num_epochs: 100
  lr: [0.01, 0.01, 0.01]
  warmups: [9,18,58]
  power: 0.1
  optimizer: sgd
  decay_rate: 0.99
  weight_decay: 0.05
  weight_decay_end: 0.04
  val_training: True
  resume: True

finetune:
  checkpoint: Rendezvous

dataset:
  batch_size: 64
  num_workers: 4
  kfold: 1
  data_dir: '/root/.cache/huggingface/forget/datasets/CholecT45/'
  dataset_variant: 'cholect45-crossval'
  pin_memory: True
  persistent_workers: True
  drop_last: False
  weight_randa: True
  data_augmentations: ['original', 'vflip', 'hflip', 'contrast', 'rot90']